-- 修复自增ID问题
-- DuckDB 需要使用 GENERATED BY DEFAULT AS IDENTITY 来实现自增

-- 1. 备份现有数据
CREATE TABLE IF NOT EXISTS sector_strength_results_backup AS
SELECT * FROM sector_strength_results;

CREATE TABLE IF NOT EXISTS sector_strength_history_backup AS
SELECT * FROM sector_strength_history;

-- 2. 删除旧表
DROP TABLE IF EXISTS sector_strength_results;
DROP TABLE IF EXISTS sector_strength_history;
DROP VIEW IF EXISTS v_latest_sector_strength;

-- 3. 重新创建表（带自增ID）
CREATE SEQUENCE IF NOT EXISTS sector_strength_results_id_seq START 1;
CREATE TABLE sector_strength_results (
    id INTEGER PRIMARY KEY DEFAULT nextval('sector_strength_results_id_seq'),
    sector_id INTEGER NOT NULL,
    sector_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    category_id INTEGER,
    category_name VARCHAR(100),

    calc_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    total_count INTEGER DEFAULT 0,
    up_count INTEGER DEFAULT 0,
    down_count INTEGER DEFAULT 0,
    up_ratio REAL DEFAULT 0,

    avg_change_pct REAL DEFAULT 0,
    avg_volume_ratio REAL DEFAULT 0,
    avg_turnover_rate REAL DEFAULT 0,

    total_net_money_flow REAL DEFAULT 0,
    avg_money_flow_ratio REAL DEFAULT 0,

    strength_score REAL DEFAULT 0,
    top_stocks TEXT,

    data_source VARCHAR(50) DEFAULT 'tushare',
    is_active BOOLEAN DEFAULT true
);

CREATE SEQUENCE IF NOT EXISTS sector_strength_history_id_seq START 1;
CREATE TABLE sector_strength_history (
    id INTEGER PRIMARY KEY DEFAULT nextval('sector_strength_history_id_seq'),
    sector_id INTEGER NOT NULL,
    calc_date DATE NOT NULL,
    strength_score REAL NOT NULL,
    avg_change_pct REAL NOT NULL,
    up_ratio REAL NOT NULL,
    total_net_money_flow REAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 恢复数据（如果有）
INSERT INTO sector_strength_results
SELECT * FROM sector_strength_results_backup
WHERE EXISTS (SELECT 1 FROM sector_strength_results_backup LIMIT 1);

INSERT INTO sector_strength_history
SELECT * FROM sector_strength_history_backup
WHERE EXISTS (SELECT 1 FROM sector_strength_history_backup LIMIT 1);

-- 5. 重新创建索引
CREATE INDEX idx_sector_strength_sector_id ON sector_strength_results(sector_id);
CREATE INDEX idx_sector_strength_category_id ON sector_strength_results(category_id);
CREATE INDEX idx_sector_strength_calc_date ON sector_strength_results(calc_date);
CREATE INDEX idx_sector_strength_composite ON sector_strength_results(sector_id, calc_date);

CREATE INDEX idx_sector_strength_history_sector_date ON sector_strength_history(sector_id, calc_date);

-- 6. 重新创建视图
CREATE OR REPLACE VIEW v_latest_sector_strength AS
SELECT
    s.*,
    ROW_NUMBER() OVER (PARTITION BY s.sector_id ORDER BY s.calc_date DESC) as rn
FROM sector_strength_results s
WHERE s.is_active = true;

-- 7. 清理备份表
DROP TABLE IF EXISTS sector_strength_results_backup;
DROP TABLE IF EXISTS sector_strength_history_backup;
